apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: x-hospital-api-mongodb-init
    files:
      - params/init-db.js
  - name: x-hospital-api-config
    literals:
      - database=x-hospital
      - collection=hospital
patches:
  - path: patches/webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: x-hospital-api
