kind: Service
apiVersion: v1
metadata:
  name: ot-hospital-api
spec:
  selector:
    pod: ot-hospital-api-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
