/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"github.com/gin-gonic/gin"
)

type HospitalRolesAPI interface {


    // GetRoles Get /api/employee-list/:hospitalId/role
    // Provides the list of roles associated with hospital 
     GetRoles(c *gin.Context)

}