/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type TransferEmployeeListEntryRequest struct {

	// The hospital to move this entry into
	TargetHospitalId string `json:"targetHospitalId"`
}
