/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

// Role - Describes employee position in hospital
type Role struct {

	Value string `json:"value"`

	Code string `json:"code,omitempty"`
}
