/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type Hospital struct {

	// Unique identifier of the hospital
	Id string `json:"id"`

	// Human readable display name of the hospital
	Name string `json:"name"`

	Address string `json:"address,omitempty"`

	EmployeeList []EmployeeListEntry `json:"employeeList,omitempty"`

	PredefinedRoles []Role `json:"predefinedRoles,omitempty"`
}
