/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the HospitalEmployeeListAPI part of the API
	HospitalEmployeeListAPI HospitalEmployeeListAPI
	// Routes for the HospitalRolesAPI part of the API
	HospitalRolesAPI HospitalRolesAPI
	// Routes for the HospitalsAPI part of the API
	HospitalsAPI HospitalsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"CreateEmployeeListEntry",
			http.MethodPost,
			"/api/employee-list/:hospitalId/entries",
			handleFunctions.HospitalEmployeeListAPI.CreateEmployeeListEntry,
		},
		{
			"DeleteEmployeeListEntry",
			http.MethodDelete,
			"/api/employee-list/:hospitalId/entries/:entryId",
			handleFunctions.HospitalEmployeeListAPI.DeleteEmployeeListEntry,
		},
		{
			"GetEmployeeListEntries",
			http.MethodGet,
			"/api/employee-list/:hospitalId/entries",
			handleFunctions.HospitalEmployeeListAPI.GetEmployeeListEntries,
		},
		{
			"GetEmployeeListEntry",
			http.MethodGet,
			"/api/employee-list/:hospitalId/entries/:entryId",
			handleFunctions.HospitalEmployeeListAPI.GetEmployeeListEntry,
		},
		{
			"TransferEmployeeListEntry",
			http.MethodPost,
			"/api/employee-list/:hospitalId/entries/:entryId/transfer",
			handleFunctions.HospitalEmployeeListAPI.TransferEmployeeListEntry,
		},
		{
			"UpdateEmployeeListEntry",
			http.MethodPut,
			"/api/employee-list/:hospitalId/entries/:entryId",
			handleFunctions.HospitalEmployeeListAPI.UpdateEmployeeListEntry,
		},
		{
			"GetPerformanceEntries",
			http.MethodGet,
			"/api/employee-list/:hospitalId/entries/:entryId/performances",
			handleFunctions.HospitalEmployeeListAPI.GetPerformanceEntries,
		},
		{
			"CreatePerformanceEntry",
			http.MethodPost,
			"/api/employee-list/:hospitalId/entries/:entryId/performances",
			handleFunctions.HospitalEmployeeListAPI.CreatePerformanceEntry,
		},
		{
			"GetPerformanceEntry",
			http.MethodGet,
			"/api/employee-list/:hospitalId/entries/:entryId/performances/:performanceId",
			handleFunctions.HospitalEmployeeListAPI.GetPerformanceEntry,
		},
		{
			"UpdatePerformanceEntry",
			http.MethodPut,
			"/api/employee-list/:hospitalId/entries/:entryId/performances/:performanceId",
			handleFunctions.HospitalEmployeeListAPI.UpdatePerformanceEntry,
		},
		{
			"DeletePerformanceEntry",
			http.MethodDelete,
			"/api/employee-list/:hospitalId/entries/:entryId/performances/:performanceId",
			handleFunctions.HospitalEmployeeListAPI.DeletePerformanceEntry,
		},
		{
			"GetRoles",
			http.MethodGet,
			"/api/employee-list/:hospitalId/role",
			handleFunctions.HospitalRolesAPI.GetRoles,
		},
		{
			"CreateHospital",
			http.MethodPost,
			"/api/hospital",
			handleFunctions.HospitalsAPI.CreateHospital,
		},
		{
			"DeleteHospital",
			http.MethodDelete,
			"/api/hospital/:hospitalId",
			handleFunctions.HospitalsAPI.DeleteHospital,
		},
		{
			"GetHospital",
			http.MethodGet,
			"/api/hospital",
			handleFunctions.HospitalsAPI.GetHospital,
		},
	}
}
